language: node_js
node_js:
 - "7"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg .

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.8 bash)"
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u github.com/elazarl/go-bindata-assetfs/...
  - go generate

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  yarn: true
  directories:
    - $HOME/.yarn
    - web/node_modules
