sudo: required
language: node_js
node_js:
 - "7"

services:
  - docker

script:
  - go generate ./web ./...
  - ./travis/coverage.sh
  - gox -os "linux darwin windows" -arch "amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - mkdir -p $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG}/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - cd $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.8 bash)"

install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u github.com/elazarl/go-bindata-assetfs/...
  - go get -u github.com/aandryashin/matchers
  - go get -u github.com/mitchellh/gox # cross compile
  - npm install cross-env

after_success:
- bash <(curl -s https://codecov.io/bash)
- cp dist/selenoid-ui_linux_amd64 ./selenoid-ui

deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: travis/docker-push.sh latest
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: travis/docker-push.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true

cache:
  yarn: true
  directories:
    - web/node_modules
